global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "event-collector"
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["event-collector:8080"]

  - job_name: "stream-processor"
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["stream-processor:8082"]

  - job_name: "insights-api"
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["insights-api:8081"]
