server:
  port: 8080

spring:
  application:
    name: event-collector
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:29092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: "1"
      retries: 3
      properties:
        spring.json.add.type.headers: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  metrics:
    export:
      prometheus:
        enabled: true

adtech:
  valid-tenants: amazon,flipkart,walmart
  kafka:
    topics:
      ad-events: ad-events
      product-events: product-events
      cart-events: cart-events
